### ISSUE TITLE
Hi friend, could you please update for osx-arm64?

### ISSUE THREAD

**Issue by ghost** [Eliav2/tkinterdnd2#4]
I need tkinterdnd2 for osx arm64 on my M1 Max Mac. I have built an arm64 version from the petasis/tkdnd repository, which can be found in the runtime-arm64.zip file. Alternatively, you can build it yourself on your M1 Mac by following the instructions provided in my issue opened on petasis/tkdnd#54.

**Comment by Squiblydoo** [comment]
The OP ended up building binaries themselves and making the repository `tkinterdnd2-universal`. They deleted the github repo but left the PyPI package. Binaries from the PyPI package have now been included in this repository. The logic was also updated to support ARM Windows, ARM MacOS, and ARM Linux. 

Someone else forked `tkinterdnd2-universal` before its deletion and it now exists solely for ARM support: https://github.com/escoolioinglesias/tkinterdnd2-osxarm64

However, these binaries have been included with an aim for supporting those architectures now and into the future.
