### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by Squiblydoo** [Eliav2/tkinterdnd2#5]
Hi Eliav2,
Someone recently reached out to me because tkinterdnd2 relies on `Tix` and `Tkinter.tix` which was [depreciated in python 3.6](https://wiki.python.org/moin/Tix) and was [removed in python 3.13](https://github.com/python/cpython/issues/75552) after having not been maintained for 10 years. 

For my personal use of tkinterdnd2, I have forked your repository and am looking at making the necessary changes to remove Tix and ensure support for python 3.13 and greater.

Do you still have interest in maintaining the tkinterdnd2 repository and pypi package? I ask because I see you are active on GitHub, but appear inactive in this repository. I am currently looking to see what improvements I can make for my own implementation, but would be happy to talk more about collaborating or taking more responsibility of the repository since tkinterdnd2 remains a [popular and important repository](https://pypistats.org/packages/tkinterdnd2).
(Feel free to reply here or reach out via the email in my profile.)
Cheers

**Comment by jessielw** [comment]
Let me know @Squiblydoo if you need help, if the original maintainer doesn't follow up.

**Comment by Squiblydoo** [comment]
@jessielw I am now a maintainer of this repo and the PyPI. Do you mind giving me a quick sanity check on my PR? https://github.com/Eliav2/tkinterdnd2/pull/6 

If it looks good to you, I'll merge it. I explained my understanding of the changes in the comments in that Pull Request. After that, I'll close this issue as resolved.

**Comment by Eliav2** [comment]
I friends sorry I missed these comments. @Squiblydoo is now maintainer and have access to the repo and the Pypi project

**Comment by Squiblydoo** [comment]
No worries, friend; we appreciate the work you did years ago to make it easily available, and your help now to make sure it stays accessible.
